# Generated by Django 3.2.3 on 2021-06-01 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=200)),
                ('cycle_start', models.DateField(verbose_name='Cycle Start Date')),
                ('cycle_end', models.DateField(verbose_name='Cycle End Date')),
                ('squat_max', models.IntegerField()),
                ('bench_max', models.IntegerField()),
                ('deadlift_max', models.IntegerField()),
                ('ohp_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('set', models.IntegerField()),
                ('lift', models.CharField(choices=[('S', 'Squat'), ('B', 'Bench'), ('D', 'Deadlift'), ('O', 'OHP')], max_length=1)),
                ('reps', models.IntegerField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cycle')),
            ],
        ),
    ]
