# Generated by Django 3.2.3 on 2021-06-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle_end',
            field=models.DateField(blank=True, null=True, verbose_name='Cycle End Date'),
        ),
    ]
