# Generated by Django 3.2.3 on 2021-06-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cycle_cycle_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
