# Generated by Django 3.2.3 on 2021-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_workout_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
