# Generated by Django 3.2.3 on 2021-06-03 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_workout_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='weight',
        ),
        migrations.AddField(
            model_name='workout',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=20)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workout')),
            ],
        ),
    ]
