# Generated by Django 3.2.3 on 2021-06-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210603_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='amrap_reps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
