# Generated by Django 3.2.3 on 2021-06-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_workout_amrap_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='tracker.cycle'),
        ),
    ]
