# Generated by Django 3.2.3 on 2021-06-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210605_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_lift', models.CharField(max_length=200)),
                ('set_number', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=20)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='tracker.workout')),
            ],
        ),
    ]
