# Generated by Django 3.2.3 on 2021-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_accessories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_number']},
        ),
        migrations.AddField(
            model_name='workout',
            name='estimated_1rm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
