# Generated by Django 3.2.3 on 2021-06-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210607_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryLift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=20)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('accessory_lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='tracker.accessorylift')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='tracker.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
