# Generated by Django 3.2.3 on 2021-06-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20210610_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessorylog',
            old_name='set_number',
            new_name='sets',
        ),
        migrations.AddField(
            model_name='accessorylift',
            name='body_part_group',
            field=models.CharField(default='whatever', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessorylog',
            name='accessory_lift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_lift', to='tracker.accessorylift'),
        ),
    ]
