# Generated by Django 3.2.13 on 2022-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='serving_grams',
            new_name='serving_unit',
        ),
        migrations.AddField(
            model_name='food',
            name='uom',
            field=models.CharField(choices=[('g', 'grams'), ('oz', 'ounces'), ('qty', 'quantity')], default='g', max_length=10),
            preserve_default=False,
        ),
    ]
