# Generated by Django 3.2.13 on 2022-04-16 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorietracker', '0002_auto_20220416_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlogitem',
            old_name='grams_eaten',
            new_name='units_eaten',
        ),
        migrations.RemoveField(
            model_name='foodlogitem',
            name='food_log',
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='date_eaten',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlogitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='uom',
            field=models.CharField(choices=[('g', 'grams'), ('oz', 'ounces'), ('qty', 'quantity')], max_length=10, verbose_name='Unit of Measurement'),
        ),
        migrations.DeleteModel(
            name='FoodLog',
        ),
    ]
