# Generated by Django 3.2.10 on 2022-04-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0004_calorieprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_unit',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
