# Generated by Django 3.2.10 on 2022-04-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0005_auto_20220417_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name']},
        ),
    ]
