# Generated by Django 3.2.13 on 2022-04-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0007_foodlogitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlogitem',
            name='category',
            field=models.CharField(choices=[('1', 'Breakfast'), ('2', 'Lunch'), ('3', 'Dinner'), ('4', 'Snack')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='units_eaten',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
