# Generated by Django 3.2.13 on 2022-04-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0009_integrationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationprofile',
            name='todoist_target_project',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
