# Generated by Django 3.2.13 on 2022-05-01 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    FoodLog = apps.get_model("calorietracker", "FoodLog")
    FoodLogItem = apps.get_model("calorietracker", "FoodLogItem")
    db_alias = schema_editor.connection.alias
    try:
        obj_list = []
        qs = FoodLogItem.objects.using(db_alias).order_by("user", "date_eaten").distinct("user", "date_eaten")
        for item in qs:
            fl = FoodLog(user=item.user, date=item.date_eaten)
            obj_list.append(fl)
        FoodLog.objects.using(db_alias).bulk_create(obj_list, ignore_conflicts=True)
    except FoodLogItem.DoesNotExist:
        pass


def backwards_func(apps, schema_editor):
    FoodLog = apps.get_model("calorietracker", "FoodLog")
    db_alias = schema_editor.connection.alias
    FoodLog.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calorietracker', '0010_integrationprofile_todoist_target_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='foodlog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique Foodlog per user'),
        ),
        migrations.RunPython(forwards_func, backwards_func)
    ]
