# Generated by Django 3.2.13 on 2022-05-01 05:39

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    FoodLog = apps.get_model("calorietracker", "FoodLog")
    FoodLogItem = apps.get_model("calorietracker", "FoodLogItem")
    db_alias = schema_editor.connection.alias
    try:
        for item in FoodLogItem.objects.using(db_alias).all():
            food_log = FoodLog.objects.filter(user=item.user).filter(date=item.date_eaten).get()
            item.food_log = food_log
            item.save()
    except FoodLogItem.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0011_auto_20220430_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlogitem',
            name='food_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log_items', to='calorietracker.foodlog', null=True),
        ),
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='foodlogitem',
            name='date_eaten',
        ),
        migrations.RemoveField(
            model_name='foodlogitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='foodlogitem',
            name='food_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_log_items',
                                    to='calorietracker.foodlog'),
        ),
    ]
