# Generated by Django 3.2.13 on 2022-05-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0012_auto_20220430_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlogitem',
            options={'ordering': ['category']},
        ),
    ]
