# Generated by Django 3.2.13 on 2023-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weighttracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightlog',
            name='trend',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
